Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Thu Nov  2 14:57:53 GMT 2023
/home1/datahome/mdemol/historical_analysis/launch/jlab.py:29: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif dashinfo is not "0":
/home1/datahome/mdemol/historical_analysis/launch/jlab.py:32: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if dashinfo is not "0":
[I 2023-11-02 14:57:53.934 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-11-02 14:57:53.956 ServerApp] Package jupyter_lsp took 0.0214s to import
[W 2023-11-02 14:57:53.956 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-02 14:57:53.964 ServerApp] Package jupyter_server_terminals took 0.0083s to import
[I 2023-11-02 14:57:53.965 ServerApp] Package notebook took 0.0000s to import
[I 2023-11-02 14:57:53.967 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-11-02 14:57:53.967 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-02 14:57:55.472 ServerApp] Package panel.io.jupyter_server_extension took 1.5042s to import
[I 2023-11-02 14:57:55.473 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-11-02 14:57:55.477 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-11-02 14:57:55.482 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-11-02 14:57:55.484 JupyterNotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-11-02 14:57:55.488 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2023-11-02 14:57:55.488 ServerApp] notebook | extension was successfully linked.
[I 2023-11-02 14:57:55.869 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-11-02 14:57:55.870 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2023-11-02 14:57:55.907 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-11-02 14:57:55.909 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-11-02 14:57:55.911 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-11-02 14:57:55.914 LabApp] JupyterLab extension loaded from /home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyterlab
[I 2023-11-02 14:57:55.914 LabApp] JupyterLab application directory is /home1/datahome/mdemol/.miniconda3/envs/histenv2/share/jupyter/lab
[I 2023-11-02 14:57:55.915 LabApp] Extension Manager is 'pypi'.
[I 2023-11-02 14:57:55.918 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-11-02 14:57:55.921 ServerApp] notebook | extension was successfully loaded.
[I 2023-11-02 14:57:55.922 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2023-11-02 14:57:55.923 ServerApp] Serving notebooks from local directory: /home1/datahome/mdemol
[I 2023-11-02 14:57:55.923 ServerApp] Jupyter Server 2.9.1 is running at:
[I 2023-11-02 14:57:55.923 ServerApp] http://r2i0n25:8877/lab
[I 2023-11-02 14:57:55.923 ServerApp]     http://127.0.0.1:8877/lab
[I 2023-11-02 14:57:55.923 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2023-11-02 14:57:55.961 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-11-02 14:57:56.024 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179?1698937075900 (10.148.1.145): Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179
[W 2023-11-02 14:57:56.025 ServerApp] wrote error: 'Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179)
[W 2023-11-02 14:57:56.027 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179?1698937075900 (561c211cf284414792903f89972ed90c@10.148.1.145) 3.58ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:57:56.916 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179/channels?session_id=4b067e18-b300-4676-98e9-d8e04f5103ae (10.148.1.145): Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179
[W 2023-11-02 14:57:56.942 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179/channels?session_id=4b067e18-b300-4676-98e9-d8e04f5103ae (561c211cf284414792903f89972ed90c@10.148.1.145) 26.23ms referer=None
[W 2023-11-02 14:57:57.070 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179?1698937076992 (10.148.1.145): Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179
[W 2023-11-02 14:57:57.070 ServerApp] wrote error: 'Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179)
[W 2023-11-02 14:57:57.070 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179?1698937076992 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.94ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:57:57.786 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179/channels?session_id=4b067e18-b300-4676-98e9-d8e04f5103ae (10.148.1.145): Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179
[W 2023-11-02 14:57:57.786 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179/channels?session_id=4b067e18-b300-4676-98e9-d8e04f5103ae (561c211cf284414792903f89972ed90c@10.148.1.145) 0.98ms referer=None
[W 2023-11-02 14:57:57.898 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179?1698937077818 (10.148.1.145): Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179
[W 2023-11-02 14:57:57.898 ServerApp] wrote error: 'Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179)
[W 2023-11-02 14:57:57.898 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179?1698937077818 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.86ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:58:01.056 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5?1698937080930 (10.148.1.145): Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5
[W 2023-11-02 14:58:01.056 ServerApp] wrote error: 'Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5)
[W 2023-11-02 14:58:01.056 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5?1698937080930 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.19ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:58:01.304 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5/channels?session_id=ef1c6aaa-183b-4171-961c-7262f808fbe5 (10.148.1.145): Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5
[W 2023-11-02 14:58:01.304 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5/channels?session_id=ef1c6aaa-183b-4171-961c-7262f808fbe5 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.05ms referer=None
[W 2023-11-02 14:58:01.446 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5?1698937081367 (10.148.1.145): Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5
[W 2023-11-02 14:58:01.446 ServerApp] wrote error: 'Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5)
[W 2023-11-02 14:58:01.446 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5?1698937081367 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.88ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:58:03.130 ServerApp] 404 GET /api/kernels/510090b6-9264-4a88-b023-a968805c2114?1698937083043 (10.148.1.145): Kernel does not exist: 510090b6-9264-4a88-b023-a968805c2114
[W 2023-11-02 14:58:03.130 ServerApp] wrote error: 'Kernel does not exist: 510090b6-9264-4a88-b023-a968805c2114'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 510090b6-9264-4a88-b023-a968805c2114)
[W 2023-11-02 14:58:03.130 ServerApp] 404 GET /api/kernels/510090b6-9264-4a88-b023-a968805c2114?1698937083043 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.85ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:58:03.530 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5/channels?session_id=ef1c6aaa-183b-4171-961c-7262f808fbe5 (10.148.1.145): Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5
[W 2023-11-02 14:58:03.530 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5/channels?session_id=ef1c6aaa-183b-4171-961c-7262f808fbe5 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.13ms referer=None
[W 2023-11-02 14:58:03.636 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5?1698937083555 (10.148.1.145): Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5
[W 2023-11-02 14:58:03.636 ServerApp] wrote error: 'Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5)
[W 2023-11-02 14:58:03.636 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5?1698937083555 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.86ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:58:03.782 ServerApp] 404 GET /api/kernels/510090b6-9264-4a88-b023-a968805c2114/channels?session_id=76da0eed-d9d7-4536-9b4a-42dc2caf9c48 (10.148.1.145): Kernel does not exist: 510090b6-9264-4a88-b023-a968805c2114
[W 2023-11-02 14:58:03.782 ServerApp] 404 GET /api/kernels/510090b6-9264-4a88-b023-a968805c2114/channels?session_id=76da0eed-d9d7-4536-9b4a-42dc2caf9c48 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.93ms referer=None
[W 2023-11-02 14:58:03.858 ServerApp] 404 GET /api/kernels/510090b6-9264-4a88-b023-a968805c2114?1698937083779 (10.148.1.145): Kernel does not exist: 510090b6-9264-4a88-b023-a968805c2114
[W 2023-11-02 14:58:03.858 ServerApp] wrote error: 'Kernel does not exist: 510090b6-9264-4a88-b023-a968805c2114'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 510090b6-9264-4a88-b023-a968805c2114)
[W 2023-11-02 14:58:03.858 ServerApp] 404 GET /api/kernels/510090b6-9264-4a88-b023-a968805c2114?1698937083779 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.85ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:58:04.010 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179/channels?session_id=4b067e18-b300-4676-98e9-d8e04f5103ae (10.148.1.145): Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179
[W 2023-11-02 14:58:04.010 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179/channels?session_id=4b067e18-b300-4676-98e9-d8e04f5103ae (561c211cf284414792903f89972ed90c@10.148.1.145) 0.93ms referer=None
[W 2023-11-02 14:58:04.084 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5/channels?session_id=ef1c6aaa-183b-4171-961c-7262f808fbe5 (10.148.1.145): Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5
[W 2023-11-02 14:58:04.084 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5/channels?session_id=ef1c6aaa-183b-4171-961c-7262f808fbe5 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.95ms referer=None
[W 2023-11-02 14:58:04.085 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179?1698937084005 (10.148.1.145): Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179
[W 2023-11-02 14:58:04.085 ServerApp] wrote error: 'Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 59b58221-f76b-4a03-979e-eb49d0968179)
[W 2023-11-02 14:58:04.086 ServerApp] 404 GET /api/kernels/59b58221-f76b-4a03-979e-eb49d0968179?1698937084005 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.85ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:58:04.170 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5?1698937084092 (10.148.1.145): Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5
[W 2023-11-02 14:58:04.170 ServerApp] wrote error: 'Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 6fedfa60-4a1b-45d6-a115-34e95aeceaf5)
[W 2023-11-02 14:58:04.170 ServerApp] 404 GET /api/kernels/6fedfa60-4a1b-45d6-a115-34e95aeceaf5?1698937084092 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.85ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 14:58:20.346 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 14:59:23.956 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-02 14:59:28.563 ServerApp] Kernel started: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 14:59:28.570 ServerApp] Kernel started: e8f7ad28-1560-4e59-8731-a1dac163666a
[I 2023-11-02 14:59:30.331 ServerApp] Kernel started: 70df7ced-0008-4314-a32c-586e28fc0b1a
readline: readline: /etc/inputrc: line 19: term: unknown variable name
/etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 14:59:57.615 ServerApp] Connecting to kernel e8f7ad28-1560-4e59-8731-a1dac163666a.
[I 2023-11-02 14:59:57.617 ServerApp] Connecting to kernel e8f7ad28-1560-4e59-8731-a1dac163666a.
[I 2023-11-02 14:59:57.619 ServerApp] Connecting to kernel e8f7ad28-1560-4e59-8731-a1dac163666a.
[I 2023-11-02 14:59:57.654 ServerApp] Connecting to kernel 70df7ced-0008-4314-a32c-586e28fc0b1a.
[I 2023-11-02 14:59:57.656 ServerApp] Connecting to kernel 70df7ced-0008-4314-a32c-586e28fc0b1a.
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 14:59:57.721 ServerApp] Connecting to kernel a56a2820-8511-4d66-88d5-d635d3cfa5c8.
[I 2023-11-02 14:59:57.879 ServerApp] Connecting to kernel 70df7ced-0008-4314-a32c-586e28fc0b1a.
[I 2023-11-02 14:59:58.011 ServerApp] Starting buffering for 70df7ced-0008-4314-a32c-586e28fc0b1a:fd32d23b-f89b-4e2b-83e8-c810e523bc03
[I 2023-11-02 15:01:28.494 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:03:29.509 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:05:30.754 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:07:32.243 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 15:07:32.562 ServerApp] /home1/datahome/mdemol/historical_analysis/.~1_zarr_coloc.ipynb doesn't exist
[I 2023-11-02 15:08:50.190 ServerApp] Kernel restarted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:08:50.354 ServerApp] Starting buffering for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
[I 2023-11-02 15:08:50.405 ServerApp] Connecting to kernel a56a2820-8511-4d66-88d5-d635d3cfa5c8.
[I 2023-11-02 15:08:50.406 ServerApp] Restoring connection for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:09:33.436 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:11:34.818 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:11:52.240 ServerApp] Kernel restarted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:11:52.306 ServerApp] Starting buffering for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
[I 2023-11-02 15:11:52.380 ServerApp] Connecting to kernel a56a2820-8511-4d66-88d5-d635d3cfa5c8.
[I 2023-11-02 15:11:52.380 ServerApp] Restoring connection for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:13:35.980 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:15:37.033 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:15:43.523 ServerApp] Kernel restarted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:15:43.567 ServerApp] Starting buffering for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
[I 2023-11-02 15:15:43.635 ServerApp] Connecting to kernel a56a2820-8511-4d66-88d5-d635d3cfa5c8.
[I 2023-11-02 15:15:43.636 ServerApp] Restoring connection for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:17:20.685 ServerApp] Kernel interrupted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:17:20.893 ServerApp] Kernel interrupted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:17:38.527 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:19:40.022 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:21:11.998 ServerApp] Kernel restarted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:21:12.132 ServerApp] Starting buffering for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
[I 2023-11-02 15:21:12.205 ServerApp] Connecting to kernel a56a2820-8511-4d66-88d5-d635d3cfa5c8.
[I 2023-11-02 15:21:12.206 ServerApp] Restoring connection for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:21:30.577 ServerApp] Kernel restarted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:21:30.614 ServerApp] Starting buffering for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
[I 2023-11-02 15:21:30.689 ServerApp] Connecting to kernel a56a2820-8511-4d66-88d5-d635d3cfa5c8.
[I 2023-11-02 15:21:30.689 ServerApp] Restoring connection for a56a2820-8511-4d66-88d5-d635d3cfa5c8:f25f2ea3-7d9d-454f-b472-a4c644125138
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:21:41.114 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:23:42.355 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:25:43.654 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:27:44.751 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:28:38.915 ServerApp] Kernel interrupted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:28:38.940 ServerApp] Kernel interrupted: a56a2820-8511-4d66-88d5-d635d3cfa5c8
Terminated
[C 2023-11-02 15:28:50.825 ServerApp] received signal 15, stopping
[I 2023-11-02 15:28:50.875 ServerApp] Shutting down 6 extensions
[I 2023-11-02 15:28:50.876 ServerApp] Shutting down 3 kernels
[I 2023-11-02 15:28:50.877 ServerApp] Kernel shutdown: e8f7ad28-1560-4e59-8731-a1dac163666a
[I 2023-11-02 15:28:50.877 ServerApp] Kernel shutdown: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[I 2023-11-02 15:28:50.877 ServerApp] Kernel shutdown: 70df7ced-0008-4314-a32c-586e28fc0b1a
